### ISSUE TITLE
User-Salt visible in plain Text

### ISSUE THREAD

**Issue by SaltatorMortis** [GWuk/PwdHash2#3]
**Is your feature request related to a problem? Please describe.**
User-Salt visible in plain Text

**Describe the solution you'd like**
add Type="password" to User-Salt input
Optional ability to store User-Salt only for the currend session
User-Salt must then be re-entered every Browser-Session via about:addon

possible storage places:
* sessionStorage
* Variable inside addon Backgroundpage

Optional hide Iteration after setting for additional security 
only after (manually) changing this Value, the edited Value would be used to generate a new Hash

**Describe alternatives you've considered**
add Type="password" to User-Salt input

**Comment by GWuk** [comment]
I don't see any issue with the salt visible in plain text:
1. yes, the threat model in mind for pwdhash does not include an untrusted local environment (i.e. someone looking over your shoulder) or a compromised workstation. I will stick to this, because it's not solveable (think of keyloggers etc).
2.  salt and iteration count need not be encrypted, see for example https://security.stackexchange.com/questions/17421/how-to-store-salt for discussion.

And I also really dislike type=password fields: they just make it more difficult to use good, long password phrases while even causing an false feeling of security (see threat model above).

**Comment by SaltatorMortis** [comment]
ok if this isnt in the scope of the thread level for this addon
its simple to fix/have a DIY solution that i sideload temporary on external mashines
